notifications:
  email: false

os: osx

language: c

git:
  depth: 3

env:
  - COLUMNS=78
before_install:
  - ./macports/bootstrap.sh
  - unset CC && source /opt/local/share/macports/setupenv.bash
script:
  - sed -i '' "s|@@REPO_PATH@@|${PWD}|g" macports/mail/neomutt-mp/Portfile
  - echo "file://${PWD}/macports" | sudo tee -a /opt/local/etc/macports/sources.conf
  - portindex -e macports
  - sudo port install neomutt-mp
  - port contents neomutt-mp
  - neomutt -v
after_failure:
  - port log neomutt-mp | tail -n 256 && sleep 8
